# golangci-lint configuration for Redis Stream Client Go
# Basic configuration compatible with Go 1.23

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - .git

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: github.com/handcoding-labs/redis-stream-client-go

  govet:
    check-shadowing: true

  lll:
    line-length: 120

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    # Only the most basic linters that don't use advanced analysis
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - typecheck     # Type-check Go code
    
    # Simple non-analysis linters
    - gocyclo       # Check cyclomatic complexity
    - goconst       # Find repeated strings that could be constants
    - gofmt         # Check if code is gofmt-ed
    - goimports     # Check imports formatting
    - misspell      # Find misspelled words
    - lll           # Check line length
    - whitespace    # Check for leading/trailing whitespace

issues:
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "exported (type|method|function) (.+) should have comment or be unexported"

  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - lll
        - gocyclo
    
    - linters:
        - lll
      source: "^//go:generate "

  max-issues-per-linter: 50
  max-same-issues: 3